DEFAULT_LOG_LEVEL = "INFO"

AMBIENT_TEMPERATURE_IN_CELSIUS = 22.0
AMBIENT_HUMIDITY_IN_PERCENT = 40.0
TURNTABLE_WEIGHT_IN_GRAMS = 420

MAIN_LOOP_TIMEOUT_IN_SECONDS = 0.01

MAGNETRON_ON_OFF_INTERVAL_IN_MS = 100
MAGNETRON_MAX_POWER_IN_WATTS = 1200
MAGNETRON_MAX_POWER_SHARE_PER_MINUTE = 0.8
MAGNETRON_MAX_TEMP_IN_CELSIUS = 200.0

COOLING_FAN_STEP_IN_PERCENT = 0.1

TURNTABLE_WEIGHT_IN_GRAMS = 420
TURNTABLE_MAX_ROTATIONS_PER_MINUTE = 5
TURNTABLE_MIN_ROTATIONS_PER_MINUTE = -5
TURNTABLE_STEP_IN_ROTATIONS_PER_MINUTE = 0.1

REFLECTOR_MAX_ANGLE_IN_DEGREES = 90.0
REFLECTOR_MIN_ANGLE_IN_DEGREES = -90.0
REFLECTOR_STEP_IN_DEGREES = 0.1
