DEFAULT_LOG_LEVEL = "INFO"

AMBIENT_TEMPERATURE_IN_CELSIUS = 22.0
AMBIENT_HUMIDITY_IN_PERCENT = 40.0
TURNTABLE_WEIGHT_IN_GRAMS = 420

MAIN_LOOP_TIMEOUT_IN_SECONDS = 0.01

MAGNETRON_ON_OFF_INTERVAL_IN_MS = 100
MAGNETRON_MAX_POWER_IN_WATTS = 1200
MAGNETRON_MAX_POWER_SHARE_PER_MINUTE = 0.8
MAGNETRON_MAX_TEMP_IN_CELSIUS = 200.0
